dist: trusty

language: node_js

node_js:
  - "9.10.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq

install:
  - npm i
  - rm -rf build/ # remove any remaining artifacts from a previous build
  - truffle version

script:
  - npm run test
  - npm run lint
  - npm run solium
notifications:
  slack: daostack:fGuaFPsiQiV5mgmzRcSzbYqw
