dist: trusty

language: node_js

node_js:
  - "10.14.2"

before_install:

install:
  - npm i
  - rm -rf build/ # remove any remaining artifacts from a previous build
  - truffle version

script:
  - npm run test
  - npm run lint
  - npm run solium
notifications:
  slack: daostack:fGuaFPsiQiV5mgmzRcSzbYqw
